import { Prisma, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedProducts() {
  const products: Prisma.ProductCreateInput[] = [
    {
      name: "Молоко пастеризоване 3.2%",
      description: "Свіже пастеризоване молоко з невисоким вмістом жиру.",
      group: "Молочні продукти",
      isAllergen: true, 
    },
    {
      name: "Сир твердий 'Бринза'",
      description: "Класичний твердий сир з традиційним смаком.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Сир плавлений",
      description: "М'який сир з легкою кремовою текстурою.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Кефір 2.5%",
      description: "Натуральний кефір з живими культурами.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Йогурт натуральний",
      description: "Натуральний йогурт без додавання цукру.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Сметана 20%",
      description: "Густая сметана з багатим смаком.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Молоко ультрапастеризоване",
      description: "Тривало зберігається без додавання консервантів.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Сир 'Фета'",
      description: "Сир за грецькою рецептурою з пікантним смаком.",
      group: "Молочні продукти",
      isAllergen: true,
    },
    {
      name: "Хліб пшеничний",
      description: "Свіжий пшеничний хліб з хрусткою скоринкою.",
      group: "Хлібобулочні вироби",
      isAllergen: true,
    },
    {
      name: "Хліб цільнозерновий",
      description: "Багатий на клітковину, виготовлений з цільнозернової муки.",
      group: "Хлібобулочні вироби",
      isAllergen: true,
    },
    {
      name: "Булка для гамбургера",
      description: "М'яка булочка, ідеальна для приготування гамбургерів.",
      group: "Хлібобулочні вироби",
      isAllergen: true,
    },
    {
      name: "Круасан",
      description: "Смачний круасан з листкового тіста.",
      group: "Хлібобулочні вироби",
      isAllergen: true,
    },
    {
      name: "Багет",
      description: "Французький багет з хрусткою кіркою.",
      group: "Хлібобулочні вироби",
      isAllergen: true,
    },
    {
      name: "Лаваш",
      description: "Тонкий лаваш, традиційний для середземноморської кухні.",
      group: "Хлібобулочні вироби",
      isAllergen: true,
    },
    {
      name: "Куряча грудка",
      description: "Ніжне м'ясо курячої грудки без кісток та шкіри.",
      group: "М'ясні продукти",
      isAllergen: false,
    },
    {
      name: "Свиняча вирізка",
      description: "Якісна вирізка зі свинини для різних страв.",
      group: "М'ясні продукти",
      isAllergen: false,
    },
    {
      name: "Яловичий стейк",
      description: "Соковитий стейк з яловичини високої якості.",
      group: "М'ясні продукти",
      isAllergen: false,
    },
    {
      name: "Сосиска куряча",
      description: "Ніжна куряча сосиска, ідеальна для сніданку.",
      group: "М'ясні продукти",
      isAllergen: false,
    },
    {
      name: "Бекон",
      description: "Хрусткий бекон з насиченим смаком.",
      group: "М'ясні продукти",
      isAllergen: false,
    },
    {
      name: "Ковбаса варена",
      description: "Класична варена ковбаса для легких закусок.",
      group: "М'ясні продукти",
      isAllergen: false,
    },
    {
      name: "Лосось філе",
      description: "Свіже філе лосося, багате на Омега-3.",
      group: "Риба та морепродукти",
      isAllergen: true, 
    },
    {
      name: "Тріска",
      description: "Ніжна тріска для запікання та варіння.",
      group: "Риба та морепродукти",
      isAllergen: true,
    },
    {
      name: "Креветки",
      description: "Свіжі креветки, багаті на білок.",
      group: "Риба та морепродукти",
      isAllergen: true,
    },
    {
      name: "Мідії",
      description: "Свіжі мідії, ідеальні для паст.",
      group: "Риба та морепродукти",
      isAllergen: true,
    },
    {
      name: "Тунець консервований",
      description: "Консервований тунець у власному соку.",
      group: "Риба та морепродукти",
      isAllergen: true,
    },
    {
      name: "Скумбрія",
      description: "Скумбрія, багата на корисні жирні кислоти.",
      group: "Риба та морепродукти",
      isAllergen: true,
    },
    {
      name: "Помідори червоні",
      description: "Соковиті червоні помідори, ідеальні для салатів.",
      group: "Овочі",
      isAllergen: false,
    },
    {
      name: "Огірки свіжі",
      description: "Хрусткі огірки для легких закусок.",
      group: "Овочі",
      isAllergen: false,
    },
    {
      name: "Морква",
      description: "Свіжа морква, багата на вітаміни.",
      group: "Овочі",
      isAllergen: false,
    },
    {
      name: "Капуста білокачанна",
      description: "Хрустка білокачанна капуста – основа багатьох страв.",
      group: "Овочі",
      isAllergen: false,
    },
    {
      name: "Броколі",
      description: "Корисні броколі, що підтримують імунітет.",
      group: "Овочі",
      isAllergen: false,
    },
    {
      name: "Салат латук",
      description: "Листя салату латук для свіжих овочевих страв.",
      group: "Овочі",
      isAllergen: false,
    },
    {
      name: "Яблука червоні",
      description: "Солодкі червоні яблука, чудові для перекусів.",
      group: "Фрукти",
      isAllergen: false,
    },
    {
      name: "Банани",
      description: "Стиглі банани з багатим смаком.",
      group: "Фрукти",
      isAllergen: false,
    },
    {
      name: "Апельсини",
      description: "Соковиті апельсини, багаті на вітамін C.",
      group: "Фрукти",
      isAllergen: false,
    },
    {
      name: "Груші",
      description: "Ніжні груші з виразним ароматом.",
      group: "Фрукти",
      isAllergen: false,
    },
    {
      name: "Ківі",
      description: "Екзотичний ківі, насичений вітамінами.",
      group: "Фрукти",
      isAllergen: false,
    },
    {
      name: "Виноград зелене",
      description: "Свіжий зелений виноград, ідеальний для перекусів.",
      group: "Фрукти",
      isAllergen: false,
    },
    {
      name: "Консервовані горошок",
      description: "Ніжний горошок у власному соку без додаткових консервантів.",
      group: "Консервація",
      isAllergen: false,
    },
    {
      name: "Консервовані кукурудзи",
      description: "Солодка кукурудза, консервована для зручності використання.",
      group: "Консервація",
      isAllergen: false,
    },
    {
      name: "Консервовані помідори",
      description: "Помідори в банках для приготування соусів та рагу.",
      group: "Консервація",
      isAllergen: false,
    },
    {
      name: "Консервована риба сардини",
      description: "Сардини у власному соку, багаті на Омега-3.",
      group: "Консервація",
      isAllergen: true,
    },
    {
      name: "Консервований ананас",
      description: "Солодкий ананас в сиропі з натуральним смаком.",
      group: "Консервація",
      isAllergen: false,
    },
    {
      name: "Мінеральна вода газована",
      description: "Освіжаюча газована мінеральна вода.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Мінеральна вода негазована",
      description: "Чиста негазована мінеральна вода.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Апельсиновий сік",
      description: "Натуральний апельсиновий сік без додавання цукру.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Яблучний сік",
      description: "Свіжовижатий яблучний сік із 100% натурального соку.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Чорний чай пакетований",
      description: "Ароматний чорний чай для класичного чаювання.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Зелений чай пакетований",
      description: "Заспокійливий зелений чай високої якості.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Кава розчинна",
      description: "Швидкий розчинний кавовий напій для бадьорого ранку.",
      group: "Напої",
      isAllergen: false,
    },
    {
      name: "Рис басматі",
      description: "Запашний рис басматі для приготування плову.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Макарони спагеті",
      description: "Тонкі спагеті з пшеничної муки, ідеальні для пасти.",
      group: "Бакалія",
      isAllergen: true,
    },
    {
      name: "Квасоля червона",
      description: "Ніжна червона квасоля – джерело білка.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Лінзи",
      description: "Багаті на залізо лінзи для здорового харчування.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Овес",
      description: "Корисний овес для приготування каш та випічки.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Пшоно",
      description: "Легко засвоюване пшоно для ситних страв.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Кіноа",
      description: "Багата білками кіноа для здорового харчування.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Шоколад молочний",
      description: "Ніжний молочний шоколад для солодкого перекусу.",
      group: "Солодощі та випічка",
      isAllergen: true,
    },
    {
      name: "Шоколад темний",
      description: "Гіркий темний шоколад без молока.",
      group: "Солодощі та випічка",
      isAllergen: false,
    },
    {
      name: "Печиво з шоколадом",
      description: "Смачне печиво з шматочками шоколаду.",
      group: "Солодощі та випічка",
      isAllergen: true,
    },
    {
      name: "Торт 'Наполеон'",
      description: "Класичний торт з ніжним кремом.",
      group: "Солодощі та випічка",
      isAllergen: true,
    },
    {
      name: "Пиріг яблучний",
      description: "Смачний яблучний пиріг з корицею.",
      group: "Солодощі та випічка",
      isAllergen: true,
    },
    {
      name: "Мафіни ванільні",
      description: "Ніжні мафіни з виразним ванільним смаком.",
      group: "Солодощі та випічка",
      isAllergen: true,
    },
    {
      name: "Заморожені овочі",
      description: "Змішаний асорті заморожених овочів для швидкого приготування.",
      group: "Заморожені продукти",
      isAllergen: false,
    },
    {
      name: "Заморожені ягоди (полуниця)",
      description: "Полуниця, заморожена для використання в смузі.",
      group: "Заморожені продукти",
      isAllergen: false,
    },
    {
      name: "Заморожена піца",
      description: "Готова піца з сиром та пепероні.",
      group: "Заморожені продукти",
      isAllergen: true,
    },
    {
      name: "Заморожене м'ясо (курка)",
      description: "Ніжне куряче м'ясо, заморожене для тривалого зберігання.",
      group: "Заморожені продукти",
      isAllergen: false,
    },
    {
      name: "Заморожені каші",
      description: "Швидко розігрівається, ідеальний сніданок.",
      group: "Заморожені продукти",
      isAllergen: false,
    },
    {
      name: "Кетчуп",
      description: "Класичний кетчуп із свіжих томатів.",
      group: "Соуси та приправи",
      isAllergen: false,
    },
    {
      name: "Майонез",
      description: "Кремовий майонез на основі яєць.",
      group: "Соуси та приправи",
      isAllergen: true,
    },
    {
      name: "Гірчиця",
      description: "Гостра гірчиця для додання смаку.",
      group: "Соуси та приправи",
      isAllergen: false,
    },
    {
      name: "Соєвий соус",
      description: "Солоний соєвий соус для азійських страв.",
      group: "Соуси та приправи",
      isAllergen: true,
    },
    {
      name: "Часниковий соус",
      description: "Смачний соус на основі свіжого часнику.",
      group: "Соуси та приправи",
      isAllergen: false,
    },
    {
      name: "Чипси картопляні",
      description: "Хрусткі картопляні чипси для легкого перекусу.",
      group: "Снеки",
      isAllergen: false,
    },
    {
      name: "Сухарики",
      description: "Смачні сухарики для супів та салатів.",
      group: "Снеки",
      isAllergen: false,
    },
    {
      name: "Горішки смажені",
      description: "Смажені горішки – смачний, але алергенний перекус.",
      group: "Снеки",
      isAllergen: true,
    },
    {
      name: "Попкорн",
      description: "Легкий попкорн для перегляду фільму.",
      group: "Снеки",
      isAllergen: false,
    },
    {
      name: "Пюре фруктове (банан)",
      description: "Ніжне фруктове пюре з бананів для малюків.",
      group: "Дитське харчування",
      isAllergen: false,
    },
    {
      name: "Пюре овочеве (морква)",
      description: "Легке овочеве пюре з моркви для немовлят.",
      group: "Дитське харчування",
      isAllergen: false,
    },
    {
      name: "Дитяче молоко",
      description: "Спеціально розроблене молоко для немовлят.",
      group: "Дитське харчування",
      isAllergen: true,
    },
    {
      name: "Кашка дитяча",
      description: "Легка дитяча каша з злаків.",
      group: "Дитське харчування",
      isAllergen: true,
    },
    {
      name: "Протеїновий батончик",
      description: "Енергетичний батончик з високим вмістом білка.",
      group: "Дієтичні продукти",
      isAllergen: false,
    },
    {
      name: "Низькокалорійний йогурт",
      description: "Йогурт для тих, хто стежить за фігурою.",
      group: "Дієтичні продукти",
      isAllergen: true,
    },
    {
      name: "Салат з кіноа",
      description: "Свіжий салат з кіноа та овочами.",
      group: "Дієтичні продукти",
      isAllergen: false,
    },
    {
      name: "Смузі зелене",
      description: "Освіжаючий зелений смузі з огірком та шпинатом.",
      group: "Дієтичні продукти",
      isAllergen: false,
    },
    {
      name: "Морожене ванільне",
      description: "Класичне ванільне морозиво.",
      group: "Десерти",
      isAllergen: true,
    },
    {
      name: "Морожене шоколадне",
      description: "Шоколадне морозиво для справжніх ласунів.",
      group: "Десерти",
      isAllergen: true,
    },
    {
      name: "Пудинг карамельний",
      description: "Ніжний пудинг з карамельною ноткою.",
      group: "Десерти",
      isAllergen: true,
    },
    {
      name: "Крем-брюле",
      description: "Делікатний десерт з хрусткою карамельною скоринкою.",
      group: "Десерти",
      isAllergen: true,
    },
    {
      name: "Тірамісу",
      description: "Італійський десерт з ніжним маскарпоне.",
      group: "Десерти",
      isAllergen: true,
    },
    {
      name: "Соєве молоко",
      description: "Рослинне молоко на основі сої.",
      group: "Замінники",
      isAllergen: true,
    },
    {
      name: "Мигдальне молоко",
      description: "Молоко, отримане з мигдалю, для веганів.",
      group: "Замінники",
      isAllergen: true,
    },
    {
      name: "Рисове молоко",
      description: "Легке молоко з рису для тих, хто не переносить сою.",
      group: "Замінники",
      isAllergen: false,
    },
    {
      name: "Грецький салат",
      description: "Салат з помідорів, огірків, оливок та сиру фета.",
      group: "Салати готові",
      isAllergen: true,
    },
    {
      name: "Цезар салат",
      description: "Класичний салат Цезар з куркою, пармезаном і крутонами.",
      group: "Салати готові",
      isAllergen: true,
    },
    {
      name: "Салат із свіжих овочів",
      description: "Легкий салат із сезонних овочів.",
      group: "Салати готові",
      isAllergen: false,
    },
    {
      name: "Гречка",
      description: "Корисна гречана крупа для щоденного раціону.",
      group: "Бакалія",
      isAllergen: false,
    },
    {
      name: "Оливкова олія",
      description: "Натуральна оливкова олія холодного віджиму.",
      group: "Інше",
      isAllergen: false,
    },
    {
      name: "Бджільний мед",
      description: "Чистий натуральний мед з вуликів.",
      group: "Інше",
      isAllergen: false,
    },
    {
      name: "Вершкове масло",
      description: "Свіже вершкове масло з насиченим смаком.",
      group: "Інше",
      isAllergen: true,
    },
  ];

  await prisma.product.createMany({
    data: products,
    skipDuplicates: true,
  });

  console.log('Seed for products completed.');
}

seedProducts()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
